# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import logging
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    op=""
    valor=0
    valor2=0
    i=0
    cadvacio=" "
    bNuevo=True
    def setupUi(self, MainWindow):        
        logging.basicConfig(level=logging.INFO)
        logging.info('La calculadora se ha iniciado con éxito.')
        logging.info('Estas en la página principal.')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 790)
        MainWindow.setMinimumSize(QtCore.QSize(620, 790))
        MainWindow.setMaximumSize(QtCore.QSize(620, 790))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 831))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.PPrincipal = QtWidgets.QWidget()
        self.PPrincipal.setObjectName("PPrincipal")
        self.bCALbasica = QtWidgets.QPushButton(self.PPrincipal)
        self.bCALbasica.setGeometry(QtCore.QRect(30, 200, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bCALbasica.setFont(font)
        self.bCALbasica.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.bCALbasica.setObjectName("bCALbasica")
        self.bUtilidades = QtWidgets.QPushButton(self.PPrincipal)
        self.bUtilidades.setGeometry(QtCore.QRect(30, 300, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bUtilidades.setFont(font)
        self.bUtilidades.setStyleSheet("color: rgb(255, 255, 255);\n"
"BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));")
        self.bUtilidades.setObjectName("bUtilidades")
        self.labelPrincipal = QtWidgets.QLabel(self.PPrincipal)
        self.labelPrincipal.setGeometry(QtCore.QRect(30, 30, 541, 121))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrincipal.setFont(font)
        self.labelPrincipal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPrincipal.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPrincipal.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrincipal.setObjectName("labelPrincipal")
        self.labelLogo = QtWidgets.QLabel(self.PPrincipal)
        self.labelLogo.setGeometry(QtCore.QRect(30, 390, 541, 341))
        self.labelLogo.setAutoFillBackground(False)
        self.labelLogo.setStyleSheet("image: url(:/logoimg/LogoDv-removebg-preview.png);")
        self.labelLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelLogo.setText("")
        self.labelLogo.setObjectName("labelLogo")
        self.fondoP = QtWidgets.QGraphicsView(self.PPrincipal)
        self.fondoP.setGeometry(QtCore.QRect(0, 0, 620, 790))
        self.fondoP.setMinimumSize(QtCore.QSize(620, 790))
        self.fondoP.setMaximumSize(QtCore.QSize(620, 790))
        self.fondoP.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fondoP.setObjectName("fondoP")
        self.fondoP.raise_()
        self.bCALbasica.raise_()
        self.bUtilidades.raise_()
        self.labelPrincipal.raise_()
        self.labelLogo.raise_()
        self.stackedWidget.addWidget(self.PPrincipal)
        self.CBasica = QtWidgets.QWidget()
        self.CBasica.setObjectName("CBasica")
        self.bBcoma = QtWidgets.QPushButton(self.CBasica)
        self.bBcoma.setGeometry(QtCore.QRect(310, 600, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBcoma.setFont(font)
        self.bBcoma.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBcoma.setObjectName("bBcoma")
        self.bB0 = QtWidgets.QPushButton(self.CBasica)
        self.bB0.setGeometry(QtCore.QRect(170, 600, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bB0.setFont(font)
        self.bB0.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB0.setObjectName("bB0")
        self.bBDiv = QtWidgets.QPushButton(self.CBasica)
        self.bBDiv.setGeometry(QtCore.QRect(450, 280, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBDiv.setFont(font)
        self.bBDiv.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBDiv.setObjectName("bBDiv")
        self.bBPor = QtWidgets.QPushButton(self.CBasica)
        self.bBPor.setGeometry(QtCore.QRect(310, 280, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBPor.setFont(font)
        self.bBPor.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBPor.setObjectName("bBPor")
        self.bBC = QtWidgets.QPushButton(self.CBasica)
        self.bBC.setGeometry(QtCore.QRect(170, 280, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBC.setFont(font)
        self.bBC.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBC.setObjectName("bBC")
        self.bBCE = QtWidgets.QPushButton(self.CBasica)
        self.bBCE.setGeometry(QtCore.QRect(30, 280, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBCE.setFont(font)
        self.bBCE.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBCE.setObjectName("bBCE")
        self.bBMul = QtWidgets.QPushButton(self.CBasica)
        self.bBMul.setGeometry(QtCore.QRect(450, 360, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBMul.setFont(font)
        self.bBMul.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBMul.setObjectName("bBMul")
        self.bB9 = QtWidgets.QPushButton(self.CBasica)
        self.bB9.setGeometry(QtCore.QRect(310, 360, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB9.setFont(font)
        self.bB9.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB9.setObjectName("bB9")
        self.bB8 = QtWidgets.QPushButton(self.CBasica)
        self.bB8.setGeometry(QtCore.QRect(170, 360, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB8.setFont(font)
        self.bB8.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB8.setObjectName("bB8")
        self.bB7 = QtWidgets.QPushButton(self.CBasica)
        self.bB7.setGeometry(QtCore.QRect(30, 360, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB7.setFont(font)
        self.bB7.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB7.setObjectName("bB7")
        self.bBSum = QtWidgets.QPushButton(self.CBasica)
        self.bBSum.setGeometry(QtCore.QRect(450, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBSum.setFont(font)
        self.bBSum.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBSum.setObjectName("bBSum")
        self.bB6 = QtWidgets.QPushButton(self.CBasica)
        self.bB6.setGeometry(QtCore.QRect(310, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB6.setFont(font)
        self.bB6.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB6.setObjectName("bB6")
        self.bB5 = QtWidgets.QPushButton(self.CBasica)
        self.bB5.setGeometry(QtCore.QRect(170, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB5.setFont(font)
        self.bB5.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB5.setObjectName("bB5")
        self.bB4 = QtWidgets.QPushButton(self.CBasica)
        self.bB4.setGeometry(QtCore.QRect(30, 440, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB4.setFont(font)
        self.bB4.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB4.setObjectName("bB4")
        self.bBRes = QtWidgets.QPushButton(self.CBasica)
        self.bBRes.setGeometry(QtCore.QRect(450, 520, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBRes.setFont(font)
        self.bBRes.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBRes.setObjectName("bBRes")
        self.bB3 = QtWidgets.QPushButton(self.CBasica)
        self.bB3.setGeometry(QtCore.QRect(310, 520, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB3.setFont(font)
        self.bB3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB3.setObjectName("bB3")
        self.bB2 = QtWidgets.QPushButton(self.CBasica)
        self.bB2.setGeometry(QtCore.QRect(170, 520, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bB2.setFont(font)
        self.bB2.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB2.setObjectName("bB2")
        self.bB1 = QtWidgets.QPushButton(self.CBasica)
        self.bB1.setGeometry(QtCore.QRect(30, 520, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bB1.setFont(font)
        self.bB1.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bB1.setObjectName("bB1")
        self.bBIgual = QtWidgets.QPushButton(self.CBasica)
        self.bBIgual.setGeometry(QtCore.QRect(450, 600, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bBIgual.setFont(font)
        self.bBIgual.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bBIgual.setObjectName("bBIgual")
        self.lOutput = QtWidgets.QLabel(self.CBasica)
        self.lOutput.setGeometry(QtCore.QRect(30, 140, 541, 111))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lOutput.setFont(font)
        self.lOutput.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lOutput.setText("")
        self.lOutput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lOutput.setObjectName("lOutput")
        self.fondoB = QtWidgets.QGraphicsView(self.CBasica)
        self.fondoB.setGeometry(QtCore.QRect(0, 0, 620, 790))
        self.fondoB.setMinimumSize(QtCore.QSize(620, 790))
        self.fondoB.setMaximumSize(QtCore.QSize(620, 790))
        self.fondoB.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fondoB.setObjectName("fondoB")
        self.bVolverBAS = QtWidgets.QPushButton(self.CBasica)
        self.bVolverBAS.setGeometry(QtCore.QRect(30, 680, 541, 61))
        self.bVolverBAS.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bVolverBAS.setFont(font)
        self.bVolverBAS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bVolverBAS.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bVolverBAS.setObjectName("bVolverBAS")
        self.bBlogo = QtWidgets.QPushButton(self.CBasica)
        self.bBlogo.setEnabled(False)
        self.bBlogo.setGeometry(QtCore.QRect(30, 600, 121, 71))
        self.bBlogo.setStyleSheet("image: url(:/logoimg/LogoDv-removebg-preview.png);\n"
"background-color: rgb(255, 255, 255);\n"
"BORDER: 5px solid black;")
        self.bBlogo.setText("")
        self.bBlogo.setObjectName("bBlogo")
        self.lOutput_2 = QtWidgets.QLabel(self.CBasica)
        self.lOutput_2.setGeometry(QtCore.QRect(30, 20, 541, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lOutput_2.setFont(font)
        self.lOutput_2.setStyleSheet("BORDER: 5px solid black;\n"
"color: rgb(134, 134, 134);\n"
"background-color: rgb(255, 255, 255);")
        self.lOutput_2.setText("")
        self.lOutput_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lOutput_2.setObjectName("lOutput_2")
        self.fondoB.raise_()
        self.bBcoma.raise_()
        self.bB0.raise_()
        self.bBDiv.raise_()
        self.bBPor.raise_()
        self.bBC.raise_()
        self.bBCE.raise_()
        self.bBMul.raise_()
        self.bB9.raise_()
        self.bB8.raise_()
        self.bB7.raise_()
        self.bBSum.raise_()
        self.bB6.raise_()
        self.bB5.raise_()
        self.bB4.raise_()
        self.bBRes.raise_()
        self.bB3.raise_()
        self.bB2.raise_()
        self.bB1.raise_()
        self.bBIgual.raise_()
        self.lOutput.raise_()
        self.bVolverBAS.raise_()
        self.bBlogo.raise_()
        self.lOutput_2.raise_()
        self.stackedWidget.addWidget(self.CBasica)
        self.PUtildades = QtWidgets.QWidget()
        self.PUtildades.setObjectName("PUtildades")
        self.fondoUTI = QtWidgets.QGraphicsView(self.PUtildades)
        self.fondoUTI.setGeometry(QtCore.QRect(0, 0, 620, 790))
        self.fondoUTI.setMinimumSize(QtCore.QSize(620, 790))
        self.fondoUTI.setMaximumSize(QtCore.QSize(620, 790))
        self.fondoUTI.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fondoUTI.setObjectName("fondoUTI")
        self.bUIMC = QtWidgets.QPushButton(self.PUtildades)
        self.bUIMC.setGeometry(QtCore.QRect(30, 200, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bUIMC.setFont(font)
        self.bUIMC.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.bUIMC.setObjectName("bUIMC")
        self.bUR3 = QtWidgets.QPushButton(self.PUtildades)
        self.bUR3.setGeometry(QtCore.QRect(30, 300, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bUR3.setFont(font)
        self.bUR3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.bUR3.setObjectName("bUR3")
        self.bUSI = QtWidgets.QPushButton(self.PUtildades)
        self.bUSI.setGeometry(QtCore.QRect(30, 400, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bUSI.setFont(font)
        self.bUSI.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"")
        self.bUSI.setObjectName("bUSI")
        self.lTexto = QtWidgets.QLabel(self.PUtildades)
        self.lTexto.setGeometry(QtCore.QRect(30, 30, 541, 121))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lTexto.setFont(font)
        self.lTexto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.lTexto.setAlignment(QtCore.Qt.AlignCenter)
        self.lTexto.setObjectName("lTexto")
        self.bVolverUTI = QtWidgets.QPushButton(self.PUtildades)
        self.bVolverUTI.setGeometry(QtCore.QRect(30, 600, 541, 61))
        self.bVolverUTI.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bVolverUTI.setFont(font)
        self.bVolverUTI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bVolverUTI.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bVolverUTI.setObjectName("bVolverUTI")
        self.bUSI.raise_()
        self.fondoUTI.raise_()
        self.bUIMC.raise_()
        self.bUR3.raise_()
        self.lTexto.raise_()
        self.bVolverUTI.raise_()
        self.stackedWidget.addWidget(self.PUtildades)
        self.PIMC = QtWidgets.QWidget()
        self.PIMC.setObjectName("PIMC")
        self.fondoIMC = QtWidgets.QGraphicsView(self.PIMC)
        self.fondoIMC.setGeometry(QtCore.QRect(0, 0, 620, 790))
        self.fondoIMC.setMinimumSize(QtCore.QSize(620, 790))
        self.fondoIMC.setMaximumSize(QtCore.QSize(620, 790))
        self.fondoIMC.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fondoIMC.setObjectName("fondoIMC")
        self.bI7 = QtWidgets.QPushButton(self.PIMC)
        self.bI7.setGeometry(QtCore.QRect(30, 350, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI7.setFont(font)
        self.bI7.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI7.setObjectName("bI7")
        self.bI5 = QtWidgets.QPushButton(self.PIMC)
        self.bI5.setGeometry(QtCore.QRect(170, 430, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI5.setFont(font)
        self.bI5.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI5.setObjectName("bI5")
        self.bIIgual = QtWidgets.QPushButton(self.PIMC)
        self.bIIgual.setGeometry(QtCore.QRect(450, 510, 121, 151))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bIIgual.setFont(font)
        self.bIIgual.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bIIgual.setObjectName("bIIgual")
        self.bI2 = QtWidgets.QPushButton(self.PIMC)
        self.bI2.setGeometry(QtCore.QRect(170, 510, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI2.setFont(font)
        self.bI2.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI2.setObjectName("bI2")
        self.bI3 = QtWidgets.QPushButton(self.PIMC)
        self.bI3.setGeometry(QtCore.QRect(310, 510, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI3.setFont(font)
        self.bI3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI3.setObjectName("bI3")
        self.bILogo = QtWidgets.QPushButton(self.PIMC)
        self.bILogo.setEnabled(False)
        self.bILogo.setGeometry(QtCore.QRect(30, 590, 121, 71))
        self.bILogo.setStyleSheet("image: url(:/logoimg/LogoDv-removebg-preview.png);\n"
"background-color: rgb(255, 255, 255);\n"
"BORDER: 5px solid black;")
        self.bILogo.setText("")
        self.bILogo.setObjectName("bILogo")
        self.bI6 = QtWidgets.QPushButton(self.PIMC)
        self.bI6.setGeometry(QtCore.QRect(310, 430, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI6.setFont(font)
        self.bI6.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI6.setObjectName("bI6")
        self.bIComa = QtWidgets.QPushButton(self.PIMC)
        self.bIComa.setGeometry(QtCore.QRect(310, 590, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bIComa.setFont(font)
        self.bIComa.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bIComa.setObjectName("bIComa")
        self.bVolverIMC = QtWidgets.QPushButton(self.PIMC)
        self.bVolverIMC.setGeometry(QtCore.QRect(30, 670, 541, 61))
        self.bVolverIMC.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bVolverIMC.setFont(font)
        self.bVolverIMC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bVolverIMC.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bVolverIMC.setObjectName("bVolverIMC")
        self.bI9 = QtWidgets.QPushButton(self.PIMC)
        self.bI9.setGeometry(QtCore.QRect(310, 350, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI9.setFont(font)
        self.bI9.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI9.setObjectName("bI9")
        self.bI1 = QtWidgets.QPushButton(self.PIMC)
        self.bI1.setGeometry(QtCore.QRect(30, 510, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bI1.setFont(font)
        self.bI1.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI1.setObjectName("bI1")
        self.bI0 = QtWidgets.QPushButton(self.PIMC)
        self.bI0.setGeometry(QtCore.QRect(170, 590, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bI0.setFont(font)
        self.bI0.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI0.setObjectName("bI0")
        self.bIC = QtWidgets.QPushButton(self.PIMC)
        self.bIC.setGeometry(QtCore.QRect(450, 430, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bIC.setFont(font)
        self.bIC.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bIC.setObjectName("bIC")
        self.bI8 = QtWidgets.QPushButton(self.PIMC)
        self.bI8.setGeometry(QtCore.QRect(170, 350, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI8.setFont(font)
        self.bI8.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI8.setObjectName("bI8")
        self.lIAltura = QtWidgets.QLabel(self.PIMC)
        self.lIAltura.setGeometry(QtCore.QRect(330, 230, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.lIAltura.setFont(font)
        self.lIAltura.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lIAltura.setText("")
        self.lIAltura.setObjectName("lIAltura")
        self.bICE = QtWidgets.QPushButton(self.PIMC)
        self.bICE.setGeometry(QtCore.QRect(450, 350, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bICE.setFont(font)
        self.bICE.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bICE.setObjectName("bICE")
        self.bI4 = QtWidgets.QPushButton(self.PIMC)
        self.bI4.setGeometry(QtCore.QRect(30, 430, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bI4.setFont(font)
        self.bI4.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bI4.setObjectName("bI4")
        self.lIPeso = QtWidgets.QLabel(self.PIMC)
        self.lIPeso.setGeometry(QtCore.QRect(330, 90, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.lIPeso.setFont(font)
        self.lIPeso.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lIPeso.setText("")
        self.lIPeso.setObjectName("lIPeso")
        self.lPeso = QtWidgets.QLabel(self.PIMC)
        self.lPeso.setGeometry(QtCore.QRect(30, 90, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lPeso.setFont(font)
        self.lPeso.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lPeso.setAlignment(QtCore.Qt.AlignCenter)
        self.lPeso.setObjectName("lPeso")
        self.lAltura = QtWidgets.QLabel(self.PIMC)
        self.lAltura.setGeometry(QtCore.QRect(30, 230, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.lAltura.setFont(font)
        self.lAltura.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lAltura.setAlignment(QtCore.Qt.AlignCenter)
        self.lAltura.setObjectName("lAltura")
        self.stackedWidget.addWidget(self.PIMC)
        self.PR3 = QtWidgets.QWidget()
        self.PR3.setObjectName("PR3")
        self.fondoR3 = QtWidgets.QGraphicsView(self.PR3)
        self.fondoR3.setGeometry(QtCore.QRect(0, 0, 620, 790))
        self.fondoR3.setMinimumSize(QtCore.QSize(620, 790))
        self.fondoR3.setMaximumSize(QtCore.QSize(620, 790))
        self.fondoR3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.fondoR3.setObjectName("fondoR3")
        self.lInput3 = QtWidgets.QLabel(self.PR3)
        self.lInput3.setGeometry(QtCore.QRect(40, 190, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.lInput3.setFont(font)
        self.lInput3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(134, 134, 134);")
        self.lInput3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lInput3.setObjectName("lInput3")
        self.lInput2 = QtWidgets.QLabel(self.PR3)
        self.lInput2.setGeometry(QtCore.QRect(340, 50, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lInput2.setFont(font)
        self.lInput2.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(134, 134, 134);")
        self.lInput2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lInput2.setObjectName("lInput2")
        self.lInput1 = QtWidgets.QLabel(self.PR3)
        self.lInput1.setGeometry(QtCore.QRect(40, 50, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.lInput1.setFont(font)
        self.lInput1.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(134, 134, 134);")
        self.lInput1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lInput1.setObjectName("lInput1")
        self.bRLogo = QtWidgets.QPushButton(self.PR3)
        self.bRLogo.setEnabled(False)
        self.bRLogo.setGeometry(QtCore.QRect(40, 550, 121, 71))
        self.bRLogo.setStyleSheet("image: url(:/logoimg/LogoDv-removebg-preview.png);\n"
"background-color: rgb(255, 255, 255);\n"
"BORDER: 5px solid black;")
        self.bRLogo.setText("")
        self.bRLogo.setObjectName("bRLogo")
        self.bR6 = QtWidgets.QPushButton(self.PR3)
        self.bR6.setGeometry(QtCore.QRect(320, 390, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR6.setFont(font)
        self.bR6.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR6.setObjectName("bR6")
        self.bR4 = QtWidgets.QPushButton(self.PR3)
        self.bR4.setGeometry(QtCore.QRect(40, 390, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR4.setFont(font)
        self.bR4.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR4.setObjectName("bR4")
        self.bRC = QtWidgets.QPushButton(self.PR3)
        self.bRC.setGeometry(QtCore.QRect(460, 390, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bRC.setFont(font)
        self.bRC.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bRC.setObjectName("bRC")
        self.bRCE = QtWidgets.QPushButton(self.PR3)
        self.bRCE.setGeometry(QtCore.QRect(460, 310, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bRCE.setFont(font)
        self.bRCE.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bRCE.setObjectName("bRCE")
        self.bR7 = QtWidgets.QPushButton(self.PR3)
        self.bR7.setGeometry(QtCore.QRect(40, 310, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR7.setFont(font)
        self.bR7.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR7.setObjectName("bR7")
        self.bR3 = QtWidgets.QPushButton(self.PR3)
        self.bR3.setGeometry(QtCore.QRect(320, 470, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR3.setFont(font)
        self.bR3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR3.setObjectName("bR3")
        self.lOutputR3 = QtWidgets.QLabel(self.PR3)
        self.lOutputR3.setGeometry(QtCore.QRect(340, 190, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lOutputR3.setFont(font)
        self.lOutputR3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(134, 134, 134);")
        self.lOutputR3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lOutputR3.setObjectName("lOutputR3")
        self.bR8 = QtWidgets.QPushButton(self.PR3)
        self.bR8.setGeometry(QtCore.QRect(180, 310, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR8.setFont(font)
        self.bR8.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR8.setObjectName("bR8")
        self.bRCalcular = QtWidgets.QPushButton(self.PR3)
        self.bRCalcular.setGeometry(QtCore.QRect(460, 470, 121, 151))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bRCalcular.setFont(font)
        self.bRCalcular.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bRCalcular.setObjectName("bRCalcular")
        self.bR0 = QtWidgets.QPushButton(self.PR3)
        self.bR0.setGeometry(QtCore.QRect(180, 550, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bR0.setFont(font)
        self.bR0.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR0.setObjectName("bR0")
        self.bR2 = QtWidgets.QPushButton(self.PR3)
        self.bR2.setGeometry(QtCore.QRect(180, 470, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR2.setFont(font)
        self.bR2.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR2.setObjectName("bR2")
        self.bR1 = QtWidgets.QPushButton(self.PR3)
        self.bR1.setGeometry(QtCore.QRect(40, 470, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.bR1.setFont(font)
        self.bR1.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR1.setObjectName("bR1")
        self.bR5 = QtWidgets.QPushButton(self.PR3)
        self.bR5.setGeometry(QtCore.QRect(180, 390, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR5.setFont(font)
        self.bR5.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR5.setObjectName("bR5")
        self.bRComa = QtWidgets.QPushButton(self.PR3)
        self.bRComa.setGeometry(QtCore.QRect(320, 550, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bRComa.setFont(font)
        self.bRComa.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bRComa.setObjectName("bRComa")
        self.bVolverR3 = QtWidgets.QPushButton(self.PR3)
        self.bVolverR3.setGeometry(QtCore.QRect(40, 630, 541, 61))
        self.bVolverR3.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        self.bVolverR3.setFont(font)
        self.bVolverR3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bVolverR3.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bVolverR3.setObjectName("bVolverR3")
        self.bR9 = QtWidgets.QPushButton(self.PR3)
        self.bR9.setGeometry(QtCore.QRect(320, 310, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(25)
        self.bR9.setFont(font)
        self.bR9.setStyleSheet("BORDER: 5px solid black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.62, x2:0.988636, y2:0.585, stop:0.295455 rgba(221, 27, 12, 209), stop:0.829545 rgba(254, 140, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.bR9.setObjectName("bR9")
        self.stackedWidget.addWidget(self.PR3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #Calculadora básica botones
        self.bB0.clicked.connect(self.numero0)
        self.bB1.clicked.connect(self.numero1)
        self.bB2.clicked.connect(self.numero2)
        self.bB3.clicked.connect(self.numero3)
        self.bB4.clicked.connect(self.numero4)
        self.bB5.clicked.connect(self.numero5)
        self.bB6.clicked.connect(self.numero6)
        self.bB7.clicked.connect(self.numero7)
        self.bB8.clicked.connect(self.numero8)
        self.bB9.clicked.connect(self.numero9)
        self.bBcoma.clicked.connect(self.coma)
        self.bBSum.clicked.connect(self.suma)
        self.bBRes.clicked.connect(self.resta)
        self.bBDiv.clicked.connect(self.division)
        self.bBMul.clicked.connect(self.multiplicacion)
        self.bBIgual.clicked.connect(self.igual)
        self.bBC.clicked.connect(self.borrar)
        self.bBCE.clicked.connect(self.borrar1)
        
        #Calculadora Regla de 3 botones
        self.bR0.clicked.connect(self.Rnumero0)
        self.bR1.clicked.connect(self.Rnumero1)
        self.bR2.clicked.connect(self.Rnumero2)
        self.bR3.clicked.connect(self.Rnumero3)
        self.bR4.clicked.connect(self.Rnumero4)
        self.bR5.clicked.connect(self.Rnumero5)
        self.bR6.clicked.connect(self.Rnumero6)
        self.bR7.clicked.connect(self.Rnumero7)
        self.bR8.clicked.connect(self.Rnumero8)
        self.bR9.clicked.connect(self.Rnumero9)
        self.bRComa.clicked.connect(self.Rcoma)
        self.bRCalcular.clicked.connect(self.Rigual)
        self.bRC.clicked.connect(self.Rborrar)
        self.bRCE.clicked.connect(self.Rborrar1)
        
        
        #Funciones Calculadora básica
    def numero0(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"0") 
        
    def numero1(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"1")
        
    def numero2(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"2")
        
    def numero3(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"3") 
        
    def numero4(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"4")
        
    def numero5(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"5")
        
    def numero6(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"6") 
        
    def numero7(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"7")
        
    def numero8(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"8")
        
    def numero9(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"9") 
        print(cad)
        
    def coma(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+",")
        
    def suma(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"+")
        self.op="+"
        logging.info('Vas a sumar.')
        
    def resta(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"-")
        self.op="-"   
        logging.info('Vas a restar.')
        
    def division(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"/")
        self.op="/"
        logging.info('Vas a dividir.')
        
    def multiplicacion(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad+"*")
        self.op="*"       
        logging.info('Vas a multiplicar.')
        
    def igual(self):
        cad=self.lOutput.text()
        if self.op=="+":
            valor=cad.split(self.op)
            resultado=float(valor[0])+float(valor[1])
            self.lOutput_2.setText(str(cad))
            self.lOutput.setText(str(resultado))
        elif self.op=="-":
            valor=cad.split(self.op)
            resultado=float(valor[0])-float(valor[1])
            self.lOutput_2.setText(str(cad))
            self.lOutput.setText(str(resultado))  
        elif self.op=="/":
            valor=cad.split(self.op)
            resultado=float(valor[0])/float(valor[1])
            self.lOutput_2.setText(str(cad))
            self.lOutput.setText(str(resultado))
        elif self.op=="*":
            valor=cad.split(self.op)
            resultado=float(valor[0])*float(valor[1])
            self.lOutput_2.setText(str(cad))
            self.lOutput.setText(str(resultado))
            
    def borrar(self):
        cad=" "
        self.lOutput.setText(cad)
        self.lOutput_2.setText(str(cad))
        logging.info('Has borrado todas las operaciones.')
        
    def borrar1(self):
        cad=self.lOutput.text()
        self.lOutput.setText(cad[:len(cad)-1])
        logging.info('Has borrado el último dígito.')
        
        #Funciones R3
        
    def Rnumero0(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"0") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"0")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"0") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero1(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"1") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"1")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"1") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero2(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"2") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"2")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"2") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero3(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"3") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"3")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"3") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero4(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"4") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"4")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"4") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero5(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"5") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"5")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"5") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero6(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"6") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"6")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"6") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero7(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"7") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"7")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"7") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero8(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"8") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"8")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"8") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rnumero9(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"9") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"9")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"9") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
        
    def Rcoma(self):
        if self.i==0:
            if self.bNuevo==True:
                self.lInput1.setText(self.cadvacio)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+",") 
        elif self.i==1:
            if self.bNuevo==True:
                self.lInput2.setText(self.cadvacio)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+",")  
        elif self.i==2:
            if self.bNuevo==True:
                self.lInput3.setText(self.cadvacio)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+",") 
        elif self.i==3:
            self.i=0
        self.bNuevo=False
        
    def Rborrar(self):
        cad=" "
        self.lInput1.setText(cad)
        self.lInput2.setText(cad)
        self.lInput3.setText(cad)
        self.lOutputR3.setText(cad)
        self.i=0
        logging.info('Has borrado todas las operaciones.')
        
    def Rborrar1(self):
        if self.i==0:
            self.lInput1.setText(cad1)
            cad1=self.lInput1.text()
            self.lInput1.setText(cad1+"0") 
        elif self.i==1:
            self.lInput2.setText(cad2)
            cad2=self.lInput2.text()
            self.lInput2.setText(cad2+"0")  
        elif self.i==2:
            self.lInput3.setText(cad3)
            cad3=self.lInput3.text()
            self.lInput3.setText(cad3+"0") 
        elif self.i==3:
            self.i=0
        logging.info('Has borrado el último dígito.')
            
    def Rigual(self):
        self.i=self.i+1
        self.bNuevo=True
        if self.i==3:
            self.i=0

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bCALbasica.setText(_translate("MainWindow", "Calculadora básica"))
        self.bUtilidades.setText(_translate("MainWindow", "Utilidades"))
        self.labelPrincipal.setText(_translate("MainWindow", "Selecciona el tipo de calculadora"))
        self.bBcoma.setText(_translate("MainWindow", ","))
        self.bB0.setText(_translate("MainWindow", "0"))
        self.bBDiv.setText(_translate("MainWindow", "/"))
        self.bBPor.setText(_translate("MainWindow", "%"))
        self.bBC.setText(_translate("MainWindow", "C"))
        self.bBCE.setText(_translate("MainWindow", "CE"))
        self.bBMul.setText(_translate("MainWindow", "*"))
        self.bB9.setText(_translate("MainWindow", "9"))
        self.bB8.setText(_translate("MainWindow", "8"))
        self.bB7.setText(_translate("MainWindow", "7"))
        self.bBSum.setText(_translate("MainWindow", "+"))
        self.bB6.setText(_translate("MainWindow", "6"))
        self.bB5.setText(_translate("MainWindow", "5"))
        self.bB4.setText(_translate("MainWindow", "4"))
        self.bBRes.setText(_translate("MainWindow", "-"))
        self.bB3.setText(_translate("MainWindow", "3"))
        self.bB2.setText(_translate("MainWindow", "2"))
        self.bB1.setText(_translate("MainWindow", "1"))
        self.bBIgual.setText(_translate("MainWindow", "="))
        self.bVolverBAS.setText(_translate("MainWindow", "Volver"))
        self.bUIMC.setText(_translate("MainWindow", "IMC"))
        self.bUR3.setText(_translate("MainWindow", "R3"))
        self.bUSI.setText(_translate("MainWindow", "SI"))
        self.lTexto.setText(_translate("MainWindow", "Selecciona el tipo de calculadora"))
        self.bVolverUTI.setText(_translate("MainWindow", "Volver"))
        self.bI7.setText(_translate("MainWindow", "7"))
        self.bI5.setText(_translate("MainWindow", "5"))
        self.bIIgual.setText(_translate("MainWindow", "="))
        self.bI2.setText(_translate("MainWindow", "2"))
        self.bI3.setText(_translate("MainWindow", "3"))
        self.bI6.setText(_translate("MainWindow", "6"))
        self.bIComa.setText(_translate("MainWindow", ","))
        self.bVolverIMC.setText(_translate("MainWindow", "Volver"))
        self.bI9.setText(_translate("MainWindow", "9"))
        self.bI1.setText(_translate("MainWindow", "1"))
        self.bI0.setText(_translate("MainWindow", "0"))
        self.bIC.setText(_translate("MainWindow", "C"))
        self.bI8.setText(_translate("MainWindow", "8"))
        self.bICE.setText(_translate("MainWindow", "CE"))
        self.bI4.setText(_translate("MainWindow", "4"))
        self.lPeso.setText(_translate("MainWindow", "Peso"))
        self.lAltura.setText(_translate("MainWindow", "Altura"))
        self.lInput3.setText(_translate("MainWindow", "Input"))
        self.lInput2.setText(_translate("MainWindow", "Input"))
        self.lInput1.setText(_translate("MainWindow", "Input", "Introduce una abuela"))
        self.bR6.setText(_translate("MainWindow", "6"))
        self.bR4.setText(_translate("MainWindow", "4"))
        self.bRC.setText(_translate("MainWindow", "C"))
        self.bRCE.setText(_translate("MainWindow", "CE"))
        self.bR7.setText(_translate("MainWindow", "7"))
        self.bR3.setText(_translate("MainWindow", "3"))
        self.lOutputR3.setText(_translate("MainWindow", "Output"))
        self.bR8.setText(_translate("MainWindow", "8"))
        self.bRCalcular.setText(_translate("MainWindow", "="))
        self.bR0.setText(_translate("MainWindow", "0"))
        self.bR2.setText(_translate("MainWindow", "2"))
        self.bR1.setText(_translate("MainWindow", "1"))
        self.bR5.setText(_translate("MainWindow", "5"))
        self.bRComa.setText(_translate("MainWindow", ","))
        self.bVolverR3.setText(_translate("MainWindow", "Volver"))
        self.bR9.setText(_translate("MainWindow", "9"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.bCALbasica.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.CBasica))
    ui.bUtilidades.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PUtildades))
    ui.bVolverBAS.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PPrincipal))
    ui.bVolverUTI.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PPrincipal))
    ui.bUIMC.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PIMC))
    ui.bUR3.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PR3))
    ui.bVolverIMC.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PPrincipal))
    ui.bVolverR3.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.PPrincipal))
    sys.exit(app.exec_())
